# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: fasterinnerlooper.mdterm
PackageVersion: 1.1.1
InstallerType: zip
NestedInstallerType: exe
NestedInstallerFiles:
- RelativeFilePath: mdterm-win-x64\MdTerm.exe
InstallerSwitches:
  Silent: unzip
  SilentWithProgress: unzip
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/fasterinnerlooper/mdterm/releases/download/v1.1.1/mdterm-win-x64.zip
  InstallerSha256: 64ECC03E36DAD0E6B7BC505F5B62EB3D80C0281785A4158DFD1E5414DF4CCC1A
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-03-28
